### ISSUE TITLE
Remove unused assets.

### ISSUE THREAD

**Issue by MagmaSlime123** [eccentricdevotion/TARDIS-Resource-Pack#11]
Title.

Plugins that use mushrooms for decoration are using certain mushroom blockstates that TARDIS uses.
Other unused assets may also still be in the pack too.

Terra, the plugin I'm using, refuses to fix this. Don't ask me to report this to them, I tried.
Told Chew about this, they're (the plugin devs) lazy apparently.

![2022-10-05_16 46 23](https://user-images.githubusercontent.com/51277766/194183137-f3c2a8b4-ca1e-43c3-bb94-fb4b12538a6a.png)

**Comment by eccentricdevotion** [comment]
No longer relevant mushroom blocks are no longer used
