### ISSUE TITLE
Have doors be in the center.

### ISSUE THREAD

**Issue by MagmaSlime123** [eccentricdevotion/TARDIS-Resource-Pack#12]
Title.

I'd love to use this instead of an iron door, but the offset position prevents this from being possible, thus making doors kinda pointless for these setups.

(Yes, I am using Leo's pack, but both yours and theirs have this issue.)

![2024-03-20_14 02 06](https://github.com/eccentricdevotion/TARDIS-Resource-Pack/assets/51277766/c6590537-3c48-47de-932b-75a0efd8938e)

**Comment by FuzzyLeo** [comment]
personally, i think this should be done either as a second door thats centred or just centring the current door, if it were changed on the existing the classic door now serves the purpose of a 2 wide door anyway so interiors relying on it such as the hospital interior can switch it out, though ofc the best of both worlds would be to just have a centred door as a new item

**Comment by eccentricdevotion** [comment]
Should be seen to when I do https://github.com/eccentricdevotion/TARDIS/issues/833
