### ISSUE TITLE
Resource pack makes giant mushrooms look weird

### ISSUE THREAD

**Issue by etgoleski** [eccentricdevotion/TARDIS-Resource-Pack#2]
random blocks on Giant mushrooms look like tardis components or like a green tardis crashed into the mushroom

**Comment by eccentricdevotion** [comment]
Only if they're not naturally generated...

See the issue here: https://github.com/eccentricdevotion/TARDIS-Resource-Pack/issues/1 (which you probably should have checked first...)

And here: https://github.com/eccentricdevotion/TARDIS/issues/125

**Comment by eccentricdevotion** [comment]
https://www.youtube.com/watch?v=CfL7B9rQTCU
