### ISSUE TITLE
Other Resource Pack Textures

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS-Resource-Pack#5]
When another resource pack has items without custom textures, this resource pack will often override the normal textures and add a TARDIS texture. Some items with textures will also be overridden. Changing the priority of the packs fixes the latter textures, but some TARDIS textures will then become default textures, and the untextured items will stay as TARDIS items.

**Comment by eccentricdevotion** [comment]
- What is the other resource pack?
- What items/normal textures are being overridden?

There's not much I an do without the above info...

Unfortunately there is no way to define which resource pack can use which custom model data, so there are bound to be some conflicts if packs use the same number.

**Comment by DalekCraft2** [comment]
The resource pack is the Slimefun pack, and some of the overridden items are furnaces, paper, chests, dispensers, bowls, blast furnaces, leads, bricks, gunpowder, gold nuggets, blocks for TARDIS seeds, snowballs, books, wool, hoppers, clocks, enchanting tables, and hay blocks.

I think the trend is mostly textures which are used in menus override the Slimefun textures. Also, for some reason, some of them are what I think are Weeping Angels and possibly a Silurian.

**Comment by eccentricdevotion** [comment]
Link to the slimefun resource pack? - a quick google gives a whole bunch of different versions

**Comment by DalekCraft2** [comment]
https://www.planetminecraft.com/texture_pack/slimefun-texture-by-raulh22/

**Comment by eccentricdevotion** [comment]
That's a really poorly coded resource pack - every item has the same custom model data overrides as every other one regardless of whether Slimefun sets the custom model data for that item or not... There are no conflicts in custom model data numbers between TARDIS and Slimefun from what I can see, but Minecraft doesn't merge custom model data between resource packs, so the pack that has the highest priority (at the top of the list) will always win.

This could possibly be remedied somewhat by editing the Slimefun resource pack, but until Minecraft can merge the custom model data there's not much you can do
