### ISSUE TITLE
Style, Pruning, and New System for TARDIS Textures

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS-Resource-Pack#6]
This is not an issue, but more of a request:
This resource pack has a style which does not fit vanilla Minecraft, due to its much higher resolution. It also has unnecessary textures, such as the retexture of the enderman into a silent, and the retextures of every painting into science-related things. Making the resource pack use 16x16 textures and removing the unnecessary textures would make it more pleasant to use.

Another way of making it more pleasant to use would be to make the TARDIS textures not dependent on biome, as that system is likely outdated and is especially messy in TARDIS bays. It also inadvertently retextures other blocks in its biome, like furnaces into artron furnaces.

**Comment by eccentricdevotion** [comment]
The style fits the resource pack that I use when I play Minecraft (https://github.com/eccentricdevotion/Bromley-Massive-Vector), as I never use the default textures ;)

I only make the textures for my own pleasure, and seeing as they are open sourced here on Github other players are quite welcome to remix or create their own textures for the plugin. Simple enough to remove the unnecessary textures yourself...

Currently the only way to retexture blocks (like the Artron furnace) is to use Optifine's CTM feature as plugins don't have that capability, again if this is not what you like, just remove the Optifine textures from the pack. I've already removed old Optifine features from the pack and replaced them with vanilla Minecraft ones where possible.

**Comment by MagmaSlime123** [comment]
> This is not an issue, but more of a request: This resource pack has a style which does not fit vanilla Minecraft, due to its much higher resolution. It also has unnecessary textures, such as the retexture of the enderman into a silent, and the retextures of every painting into science-related things. Making the resource pack use 16x16 textures and removing the unnecessary textures would make it more pleasant to use.
> 
> Another way of making it more pleasant to use would be to make the TARDIS textures not dependent on biome, as that system is likely outdated and is especially messy in TARDIS bays. It also inadvertently retextures other blocks in its biome, like furnaces into artron furnaces.

If you do make something like this, please share it.
