### ISSUE TITLE
Use Void biome for custom textures instead of Deep_Ocean

### ISSUE THREAD

**Issue by DalekCraft2** [eccentricdevotion/TARDIS-Resource-Pack#7]
Because the Void biome is not normally present in the Overworld at all, using it for TARDIS textures instead of using the Deep_Ocean and The_End biomes would reduce chances of misplaced textures.
If you do this, be sure of that you have removed the Deep_Ocean biome in the Redstone console, if that is not just mine. Check other consoles, too.

**Comment by DalekCraft2** [comment]
![image](https://user-images.githubusercontent.com/50336832/111193759-e7763280-8590-11eb-890e-ce7995908243.png)
This is what happens with the current system, and with the Deep_Ocean biome in my TARDIS.

**Comment by eccentricdevotion** [comment]
No longer relevant, plugin texture system has changed
