### ISSUE TITLE
Bedrock textures

### ISSUE THREAD

**Issue by Batman2741** [eccentricdevotion/TARDIS-Resource-Pack#9]
Just simply texture packs to put for geyser

**Comment by eccentricdevotion** [comment]
https://rtm516.github.io/ConvertJavaTextureToBedrock/

**Comment by eccentricdevotion** [comment]
But there are likely to be issues as most of the TARDIS textures use custom model data which is not available on Bedrock

**Comment by Batman2741** [comment]
> But there are likely to be issues as most of the TARDIS textures use custom model data which is not available on Bedrock

Although I never got it to work with the converter you gave me I have recently seen custom model data done for bedrock using a mix of resource and behavior packs is there a way to do that for the TARDIS plugin

**Comment by eccentricdevotion** [comment]
https://wiki.geysermc.org/geyser/custom-items/
and
https://github.com/Kas-tle/java2bedrock.sh/issues/new?assignees=&labels=conversion&template=pack-conversion.yml&title=%5BPack%5D%3A+

I've done a conversion which you can grab from here: https://github.com/Kas-tle/java2bedrock.sh/issues/3940
I've installed it on my desktop Mac but haven't really had a chance to test it, as I got distracted from doing bedrock forms which don't need resource packs...

**Comment by eccentricdevotion** [comment]
Seems to work for items in hand, but not everything in GUIs...

1. Install mappings and .mcpack on server
2. Install addon on Bedrock device
3. Join server

![key](https://user-images.githubusercontent.com/1841924/222942104-0441a329-c91f-4e95-bfed-37d6381c4b73.jpg)

![sonic](https://user-images.githubusercontent.com/1841924/222942106-814056a8-61f0-4591-8c86-e8e00ed2b8c6.jpg)
